#Dockerfile identique à 1.10 + l'ajout du URL du backend pour faire la connectivité
FROM ubuntu:16.04
RUN apt-get update && apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash
RUN apt-get install -y nodejs
RUN apt-get install git -y
RUN git clone https://github.com/docker-hy/frontend-example-docker.git

####ajout de ENV avec le URL du backend####

ENV API_URL=http://localhost:30080

###########################################


WORKDIR /frontend-example-docker
RUN npm install
EXPOSE 5000
CMD ["npm", "start"]