apiVersion: apps/v1
kind: Deployment
metadata:
  name: projet-backend
  labels:
    app: backend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-pod
  template:
    metadata:
      labels:
        app: backend-pod
    spec:
      containers:
      - image: julien1994/projet-backend
        name: backend-container
        imagePullPolicy: Always
        env:
        - name: DB_HOST
          value: db
        - name: DB_USERNAME
          value: postgres
        - name: DB_PASSWORD
          value: crosemont
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector: 
    app: backend-pod
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080

