apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      volumes:
      - name: db-storage
        persistentVolumeClaim: 
          claimName: db-pv-claim
      containers:
      - name: db
        image: postgres
        ports:
        - containerPort: 5432
        name: db-redmine
        volumeMounts:
        - name: db-storage
          mountPath: /var/lib/postgresql/db-data
        env:
        - name: POSTGRES_PASSWORD
          value: crosemont
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec: 
  type: ClusterIP
  ports:
  - port: 5432
  selector:
    app: db

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi



