apiVersion: apps/v1
kind: Deployment
metadata:
  name: projet-frontend
  labels:
    app: frontend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-pod
  template:
    metadata:
      labels:
        app: frontend-pod
    spec:
      containers:
      - image: julien1994/projet-frontend
        name: frontend-container
        imagePullPolicy: Always
      restartPolicy: Always


---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector: 
    app: frontend-pod
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30050